### ISSUE TITLE
lots of bugs typechecking native

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1286]
These are the problems I noticed immediately, surely there are more:

- [x] All versions of the `native` dec are forced to have the exact same annotations, which is no good, for, e.g. the `doc` annotation.
- [x] This seems to be a catchall way to avoid directly checking stuff like `variable`, but if we want decent messages we _do_ have to directly check `variable` and perhaps others.
- [ ] The upper bounds of a type parameter of a `native` implementation are never checked for consistency with the header.
- [x] The members of a `native` class are never checked at all! Currently I can write a `native` implementation class which simply doesn't implement the shared members of the header.
- [x] References to a `native` dec resolve to the last `native` implementation to be declared in the file, not to the `native` header.
- [x] The following code blows everything up:

```ceylon
class X() {}
native ("jvm") class X() {}
native ("js") class X() {}
```
- [x] Another bug:

```ceylon
native variable String name;
variable String name = "Gavin";
native ("js") variable String name = "Gavin";
```
- [x] The typechecker as written will accept a native function or class implementation with no header, and then lets me call that function or class from anywhere I like, even in a native implementation for a different backend.

**Comment by gavinking** [comment]
Also: the following code blows everything up:

```ceylon
class X() {}
native ("jvm") class X() {}
native ("js") class X() {}
```

Due to completely faulty logic for initializing the `overloads` list in `DeclarationVisitor`.

**Comment by gavinking** [comment]
@quintesse Are you going to look at some of these?

**Comment by quintesse** [comment]
@gavinking yes, but right now I'm fixing an issue in the IDE first.

**Comment by gavinking** [comment]
Another bug:

```ceylon
native variable String name;
variable String name = "Gavin";
native ("js") variable String name = "Gavin";
```

This is accepted by the typechecker, when it should not be, and blows up the backend.

**Comment by gavinking** [comment]
Aw man, another huge hole. The typechecker as written will accept a `native` function or class implementation with no header, and then lets me call that function or class from anywhere I like, even in a `native` implementation _for a different backend_.

For now I'm just going to disable the ability to have header-less `natives`. But even that doesn't fully solve the problem because nothing validates that the header has "enough" native implementations.

I'm not sure if this can really go into 1.2, since the rules don't seem to have been thought through at all.

**Comment by quintesse** [comment]
> Another bug:

This one I've already fixed in my local version.

> because nothing validates that the header has "enough" native implementations.

Well actually there's a `MissingNativeVisitor` that's part of the compilers where we do the last validation check. We could require there that you always need enough implementations.

> since the rules don't seem to have been properly thought through.

Well we can just start with the version that always needs a header and extend from there.

**Comment by gavinking** [comment]
@quintesse you had better pull 'cos I have done some work on this stuff today. (It would be nice if you could _push_ too.)

**Comment by gavinking** [comment]
So the situation has improved _somewhat_ but it's still pretty bad.

1. The `native implementation not found` error is rubbish. This should be handled by the typechecker.
2. I can add a method to the native header for a class, and callers in non-native code will not see it.
3. But if I add a method to the _Java_ native implementation of the class, then suddenly callers in non-native code will _do_ see it.
4. When I add a method to the native header for a class, but forget to implement it in the native implementations, there is no error.

**Comment by gavinking** [comment]
5. I get a totally inconsistent and broken error experience if I happen to have two native implementations for the same backend, or two native headers!

**Comment by davidfestal** [comment]
@gavinking : some changes I've done in the typechecker in order to fix some of my IDE issues might have introduced some of these regressions. I'm working on it.

**Comment by quintesse** [comment]
@gavinking the item "The members of a native class are never checked at all" above is still not marked as completed, right now no validity checks are done for members.

Re point 1. I don't know how the typechecker can handle this when we're also dealing with actual native implementations written in Java and JavaScript (like in the language module). Only the backends know how to deal with that.

> Also, I get a totally inconsistent and broken error experience if I happen to have two native implementations for the same backend, or two native headers!

Can you give an example of that "inconsistent and broken error experience"?

**Comment by gavinking** [comment]
Well if I have things along the lines of:

    native("js") void goodbye(String name) {
        print("bye");
    }
    native("js") void goodbye(String name) {
        print("bye");
    }

The typechecker can _certainly_ see that there's something wrong there, but instead I get, either, a backend error from the Java compiler, or no error from the JS compiler.

If I write:

    native void goodbye(String name) {
        print("bye");
    }
    native void goodbye(String name) {
        print("bye");
    }
    native("jvm") void goodbye(String name) {
        print("bye");
    }

I get now error messages at all.

**Comment by davidfestal** [comment]
@gavinking , @quintesse : as I already said, it was introduced by one of my commits. I'm working on it to find out the best solution that will fix these new errors while allowing a correct behavior inside the IDE

**Comment by quintesse** [comment]
Ok @davidfestal , just making sure this isn't something that also affects the CLI.

**Comment by davidfestal** [comment]
it introduced regressions also for the CLI, but I'm fixing them.

**Comment by davidfestal** [comment]
I'm about to push the fix to those regressions.

**Comment by davidfestal** [comment]
@gavinking , @quintesse : that should be better. at least I've fixed the known regressions I had introduced.

**Comment by gavinking** [comment]
Another issue. I have:

```ceylon
shared native void hello() {
    doesNotExist();
}
```

There is no method `doesNotExist()` anywhere. But there's also no error from the typechecker!

**Comment by gavinking** [comment]
Alright so this is working significantly better now. But I still have this weird thing where even though references to `native` toplevel classes from non-`native` code correctly resolve to the native header, references to their _members_ for some reason resolve to the first native _implementation_. That's something that's obviously wrong in how the typechecker is resolving references to members of `native` classes. @quintesse, any idea?

**Comment by quintesse** [comment]
Yeah, this is because currently members are only added to their direct container, without using overloads. This is because we only do this "overloading" in places where it's possible to encounter duplicates, and because each member is in its own container it's not considered an overload. I'm assuming that changing that should fix it.

**Comment by gavinking** [comment]
@quintesse that explanation doesn't make sense. The qualifying reference is to the header. It should be resolving the member within the header type.

**Comment by gavinking** [comment]
Wait, OK, I was confused because the IDE looked like it was resolving the outer reference to the header but that's in fact just IDE magic. In fact it resolves the outer reference to the first `native` _implementation_!

But surely that's wrong!

**Comment by gavinking** [comment]
Yeah, I don't like what `ExpressionVisitor.nativeDeclaration()` is doing _at all_. It should leave its argument alone when we aren't inside a `native` declaration.

**Comment by quintesse** [comment]
It's only called when inside a native declaration, look at the call sites.

**Comment by gavinking** [comment]
@quintesse Not true. I saw in the debugger.

**Comment by quintesse** [comment]
Ah I think I understand what you're getting at. I think I do that only for the error checking, if that's true I can change it.

**Comment by gavinking** [comment]
I mean I'm trying to fix it myself right now.

**Comment by quintesse** [comment]
Ok, but I think I just did that. Simplifying it to not change the reference anymore didn't break anything in the CLI at least.

**Comment by gavinking** [comment]
Well eyeballing the code, that logic _still_ looks wrong. Look, just let me fix it, because I actually test things.

**Comment by quintesse** [comment]
Sure because I don't run the **entire** test suite when I make these changes.

**Comment by gavinking** [comment]
No, it's because you _never_ test anything in the IDE.

**Comment by gavinking** [comment]
@quintesse this commit @0f95aeec38b15e3dcb32e1af2cce49c75567f052 is _much_ better but still has one bug. If I reference a member of a `native` class from non-`native` code, it correctly resolves to the member of the header. But that means that if there is no native implementation of that member, no error is produced. 

But I guess that's basically just because of the lack of member validation, since in this case I should have an error in the native implementation class warning me of a missing member.

So I guess this fix is now correct, as far as it goes. WDYT?

**Comment by gavinking** [comment]
OK, so this is working _much_ better now. The big remaining problem is that for a member of a `native` class, this error message:

    No native implementation for backend: native hello is not implemented for one or more backends

only appears if _both_ `native` implementations are missing the member. i.e. it appears in this case:

```ceylon
shared native class Greeting() {
    shared native void hello();
}
shared native("jvm") class Greeting() {
}
shared native("js") class Greeting() {
}
```

But not in this case:

```
shared native class Greeting() {
    shared native void hello();
}
shared native("jvm") class Greeting() {
    shared native("jvm") void hello() => print("Hello Java");
}
shared native("js") class Greeting() {
}
```

It seems you already know that but I thought I would document it here anyway.

**Comment by gavinking** [comment]
@quintesse status? isn't it about time we got this issue closed out?

**Comment by quintesse** [comment]
The only thing in your list that is still open is "The upper bounds of a type parameter of a native implementation are never checked for consistency with the header." but that's probably because I was never really sure how to check that. So if you can tell me how I can check that two type parameters are the same I can add that test and we can close this.

**Comment by gavinking** [comment]
Well the cheap way I guess is to check that `ModelUtil.intersectionOfSupertypes()` is exactly the same type for both type parameters.

**Comment by quintesse** [comment]
Ok, done, I think we can close this now.

**Comment by quintesse** [comment]
Closing, we can create new issues for anything that we encounter from now.

**Comment by gavinking** [comment]
Excellent. Congrats!
